ktor:
  deployment:
    port: 8080
  application:
    modules:
      - server.plugins.ResourcesKt.configureResources
      - server.plugins.ContentNegotiationKt.configureContentNegotiation
      - server.controller.SafariRoutingKt.configureRouting